// Central glossary for every hover-able term in the UI. Tooltip text lives
// here so wording stays consistent across ControlBar, Inspector, node cards,
// and the palette. Edit prose here, not in components.

export interface GlossaryEntry {
  /** Label fallback when <Hint term="x"/> is used without children. */
  term: string;
  /** Plain-English explanation shown in the tooltip body. */
  full: string;
}

export const GLOSSARY = {
  // ── live metrics (node cards, inspector) ────────────────────────────
  rps: {
    term: 'rps',
    full: 'Requests per second flowing through this node. Higher = busier; compare against capacity to spot saturation.'
  },
  throughput: {
    term: 'throughput',
    full: 'Successful requests completed per second. Throughput stalls when a node hits its capacity ceiling.'
  },
  p50: {
    term: 'p50',
    full: 'Median latency — half of requests finish faster than this. Best estimate of the typical user experience.'
  },
  p99: {
    term: 'p99',
    full: '99th-percentile latency — only 1 in 100 requests is slower. The tail oncall actually feels.'
  },
  p50p99: {
    term: 'p50 / p99',
    full: 'Median (p50) and 99th-percentile (p99) request latency. Big gap = tail problem (queueing, GC, slow downstream).'
  },
  inFlight: {
    term: 'in-flight',
    full: 'Requests currently being processed by this node right now. Approaches capacity → queueing starts.'
  },
  queue: {
    term: 'queue',
    full: 'Requests waiting because capacity is full. Growing queue = backpressure; if it crosses queue-limit, new requests are dropped.'
  },
  errRate: {
    term: 'err rate',
    full: 'Share of requests that failed (drops, timeouts, faults) over the last sample window.'
  },

  // ── configurable props (inspector) ──────────────────────────────────
  capacity: {
    term: 'capacity',
    full: 'Max concurrent requests this node can process. Exceeding it pushes new arrivals into the queue.'
  },
  queueLimit: {
    term: 'queue limit',
    full: 'How many requests can wait before the node starts dropping them. Lower = fail fast, higher = absorb bursts at the cost of latency.'
  },
  hitRate: {
    term: 'hit rate',
    full: 'Fraction of cache reads served from memory (0 – 1). A miss falls through to the downstream node.'
  },
  drainRPS: {
    term: 'drain rps',
    full: 'How quickly consumers pull messages out of the queue. If incoming rate > drain rate, backlog grows.'
  },
  maxQueueSize: {
    term: 'max',
    full: 'Hard ceiling on queued messages. Once full, the producer side starts seeing failures.'
  },
  meanNs: {
    term: 'mean',
    full: 'Average service time per request, in nanoseconds. Random latency is drawn from a normal distribution around this value.'
  },
  stdNs: {
    term: 'std',
    full: 'Standard deviation of service time. Bigger std = more variance in p99 vs. p50.'
  },
  strategy: {
    term: 'strategy',
    full: 'Load-balancing policy: roundRobin, leastInFlight, or random.'
  },

  // ── control bar ─────────────────────────────────────────────────────
  speed: {
    term: 'speed',
    full: 'Simulation wall-clock multiplier. 1× = real time, 100× = compress a minute of behavior into ~0.6 s. The worker still caps each tick to keep the UI responsive.'
  },
  speedMax: {
    term: 'max',
    full: 'Run as fast as the simulator can step — useful for fast-forwarding to steady state. Per-tick budget still applies so the page stays interactive.'
  },
  scale: {
    term: 'scale',
    full: 'Global RPS dial: applies to every Traffic Source on the canvas at once. Logarithmic — small slider moves at the top change rps by thousands.'
  },
  seed: {
    term: 'seed',
    full: 'RNG seed for the simulator. Same seed + same topology + same speed = identical run. Reseed to explore a different random sample of the same system.'
  },
  born: {
    term: 'born',
    full: 'Total requests generated by all sources since the simulation started.'
  },
  done: {
    term: 'done',
    full: 'Requests that finished successfully end-to-end.'
  },
  fail: {
    term: 'fail',
    full: 'Requests dropped or failed (queue overflow, kill fault, packet loss). born = done + fail + inFlight.'
  },
  play: {
    term: 'play',
    full: 'Start the simulator with the current topology and speed.'
  },
  pause: {
    term: 'pause',
    full: 'Freeze the simulator; state is preserved and you can resume from this point.'
  },
  stop: {
    term: 'stop',
    full: 'Halt the simulator and clear all metrics. Next play starts from scratch.'
  },

  // ── chaos ───────────────────────────────────────────────────────────
  faultKill: {
    term: 'kill',
    full: 'Crash the node. All requests routed to it fail immediately until you clear the fault.'
  },
  faultSlow: {
    term: 'slow',
    full: 'Multiply this node’s service time by 10×. Watch p99 explode and queues fill upstream.'
  },
  faultLoss: {
    term: 'loss',
    full: 'Randomly drop ~50% of requests reaching this node. Models flaky network or partial outages.'
  },
  faulted: {
    term: 'faulted',
    full: 'A fault is currently injected on this node. Click the same chaos button again to clear.'
  },

  // ── palette ─────────────────────────────────────────────────────────
  components: {
    term: 'components',
    full: 'Individual building blocks. Drag onto canvas or press Enter to insert at the center.'
  },
  templates: {
    term: 'templates',
    full: 'Pre-wired starter patterns — drop one to skip the boilerplate of connecting common topologies.'
  },

  // ── inspector actions ───────────────────────────────────────────────
  duplicate: {
    term: 'duplicate',
    full: 'Copy this node with the same props, offset slightly so you can see the new one. Edges are not duplicated.'
  },
  resetProps: {
    term: 'reset',
    full: 'Restore this node’s properties to the catalog defaults for its kind. Position and connections stay.'
  },
  deleteNode: {
    term: 'delete',
    full: 'Remove this node from the canvas. Any edges touching it are removed too.'
  },
  liveMetrics: {
    term: 'live',
    full: 'Read-only snapshot from the running simulator. Updates ~30× per second; pause to freeze.'
  },
  autoClearFault: {
    term: 'auto-clear',
    full: 'Inject the fault for this many seconds, then automatically clear it. Set 0 for manual clear only.'
  },
  activeFault: {
    term: 'active',
    full: 'The fault currently injected on this node. Click another chaos button to swap, or Clear to remove.'
  },
  clearFault: {
    term: 'clear',
    full: 'Remove any active fault from this node. Equivalent to clicking the active chaos button a second time.'
  },

  // ── system-design concepts (referenced from META panel + tooltips) ──
  backpressure: {
    term: 'backpressure',
    full: 'Downstream slowness pushing back upstream — queues fill, latency climbs, eventually drops start. The healthy response is to slow the producer, not buffer indefinitely.'
  },
  tailLatency: {
    term: 'tail latency',
    full: 'The slow end of the latency distribution — p99, p999. A request that touches N services has N chances to hit a slow tail, so multi-hop systems amplify it.'
  },
  thunderingHerd: {
    term: 'thundering herd',
    full: 'Many callers simultaneously retry, reconnect, or fetch the same key — overwhelming the target right when it just recovered. Jitter your retries.'
  },
  cacheStampede: {
    term: 'cache stampede',
    full: 'A popular cache key expires; every waiting request races to repopulate it and slams the origin. Single-flight or stale-while-revalidate prevents the collapse.'
  },
  hotKey: {
    term: 'hot key',
    full: 'A single partition / cache key receives outsized traffic — bypassing the horizontal scaling that the rest of the cluster enjoys. Symptom of bad key design.'
  },
  replicationLag: {
    term: 'replication lag',
    full: 'How far behind a replica is from the primary. A read on the replica may not see a write that just committed — design read paths to tolerate this.'
  },
  consistency: {
    term: 'consistency',
    full: 'How quickly readers see a write. Strong = read sees last write immediately; eventual = read may lag but converges. Cost vs. correctness tradeoff.'
  },
  idempotency: {
    term: 'idempotency',
    full: 'Property that applying an operation N times has the same effect as once. Required for safe retries — without it, retries duplicate work.'
  },
  fanOut: {
    term: 'fan-out',
    full: 'One request triggers N parallel downstream calls. Throughput multiplies the load; tail-latency amplifies because you wait on the slowest of N.'
  },
  sharding: {
    term: 'sharding',
    full: 'Splitting data across nodes by a key (user id, tenant). Scales writes horizontally. Cross-shard queries become expensive — choose the key carefully.'
  },
  cdc: {
    term: 'CDC',
    full: 'Change Data Capture — stream every insert/update/delete from a database into a log (Kafka, etc). Lets search indexes, caches, and warehouses follow OLTP without dual writes.'
  },
  cqrs: {
    term: 'CQRS',
    full: 'Command-Query Responsibility Segregation — separate the write model from the read model, often using different stores. Lets reads scale independently of writes at the cost of more moving parts.'
  },
  saga: {
    term: 'saga',
    full: 'Multi-step distributed transaction implemented as a sequence of local commits with compensating actions on failure. Trades atomicity for availability across services.'
  },
  exactlyOnce: {
    term: 'delivery semantics',
    full: 'At-most-once = may drop; at-least-once = may duplicate; exactly-once = neither, and expensive. Most systems are at-least-once with idempotent consumers.'
  },
  circuitBreakerPattern: {
    term: 'circuit breaker',
    full: 'Wrap a downstream call: when its failure rate crosses a threshold, the breaker opens and fails fast. Stops a sick dependency from dragging the caller down with it.'
  },
  rateLimitPattern: {
    term: 'rate limiting',
    full: 'Cap how many requests a client may make per unit time. Token-bucket allows bursts up to the bucket size; sliding-window is smoother but more state. Reject early to protect downstream.'
  },
  coldStart: {
    term: 'cold start',
    full: 'First request after idle pays the cost of loading the runtime (Lambda), the model weights (ML serving), or the cache (post-deploy). Pre-warm if SLA matters.'
  },
  graceful: {
    term: 'graceful degradation',
    full: 'When a dependency fails, return a reduced answer rather than a 500. Stale cache, default values, partial results — anything that keeps the user moving.'
  }
} as const satisfies Record<string, GlossaryEntry>;

export type Term = keyof typeof GLOSSARY;
