// Central glossary for every hover-able term in the UI. Tooltip text lives
// here so wording stays consistent across ControlBar, Inspector, node cards,
// and the palette. Edit prose here, not in components.

export interface GlossaryEntry {
  /** Label fallback when <Hint term="x"/> is used without children. */
  term: string;
  /** Plain-English explanation shown in the tooltip body. */
  full: string;
}

export const GLOSSARY = {
  // ── live metrics (node cards, inspector) ────────────────────────────
  rps: {
    term: 'rps',
    full: 'Requests per second flowing through this node. Higher = busier; compare against capacity to spot saturation.'
  },
  throughput: {
    term: 'throughput',
    full: 'Successful requests completed per second. Throughput stalls when a node hits its capacity ceiling.'
  },
  p50: {
    term: 'p50',
    full: 'Median latency — half of requests finish faster than this. Best estimate of the typical user experience.'
  },
  p99: {
    term: 'p99',
    full: '99th-percentile latency — only 1 in 100 requests is slower. The tail oncall actually feels.'
  },
  p50p99: {
    term: 'p50 / p99',
    full: 'Median (p50) and 99th-percentile (p99) request latency. Big gap = tail problem (queueing, GC, slow downstream).'
  },
  inFlight: {
    term: 'in-flight',
    full: 'Requests currently being processed by this node right now. Approaches capacity → queueing starts.'
  },
  queue: {
    term: 'queue',
    full: 'Requests waiting because capacity is full. Growing queue = backpressure; if it crosses queue-limit, new requests are dropped.'
  },
  errRate: {
    term: 'err rate',
    full: 'Share of requests that failed (drops, timeouts, faults) over the last sample window.'
  },

  // ── configurable props (inspector) ──────────────────────────────────
  capacity: {
    term: 'capacity',
    full: 'Max concurrent requests this node can process. Exceeding it pushes new arrivals into the queue.'
  },
  queueLimit: {
    term: 'queue limit',
    full: 'How many requests can wait before the node starts dropping them. Lower = fail fast, higher = absorb bursts at the cost of latency.'
  },
  hitRate: {
    term: 'hit rate',
    full: 'Fraction of cache reads served from memory (0 – 1). A miss falls through to the downstream node.'
  },
  drainRPS: {
    term: 'drain rps',
    full: 'How quickly consumers pull messages out of the queue. If incoming rate > drain rate, backlog grows.'
  },
  maxQueueSize: {
    term: 'max',
    full: 'Hard ceiling on queued messages. Once full, the producer side starts seeing failures.'
  },
  meanNs: {
    term: 'mean',
    full: 'Average service time per request, in nanoseconds. Random latency is drawn from a normal distribution around this value.'
  },
  stdNs: {
    term: 'std',
    full: 'Standard deviation of service time. Bigger std = more variance in p99 vs. p50.'
  },
  strategy: {
    term: 'strategy',
    full: 'Load-balancing policy: roundRobin, leastInFlight, or random.'
  },

  // ── control bar ─────────────────────────────────────────────────────
  speed: {
    term: 'speed',
    full: 'Simulation wall-clock multiplier. 1× = real time, 100× = compress a minute of behavior into ~0.6 s. The worker still caps each tick to keep the UI responsive.'
  },
  speedMax: {
    term: 'max',
    full: 'Run as fast as the simulator can step — useful for fast-forwarding to steady state. Per-tick budget still applies so the page stays interactive.'
  },
  scale: {
    term: 'scale',
    full: 'Global RPS dial: applies to every Traffic Source on the canvas at once. Logarithmic — small slider moves at the top change rps by thousands.'
  },
  seed: {
    term: 'seed',
    full: 'RNG seed for the simulator. Same seed + same topology + same speed = identical run. Reseed to explore a different random sample of the same system.'
  },
  born: {
    term: 'born',
    full: 'Total requests generated by all sources since the simulation started.'
  },
  done: {
    term: 'done',
    full: 'Requests that finished successfully end-to-end.'
  },
  fail: {
    term: 'fail',
    full: 'Requests dropped or failed (queue overflow, kill fault, packet loss). born = done + fail + inFlight.'
  },
  play: {
    term: 'play',
    full: 'Start the simulator with the current topology and speed.'
  },
  pause: {
    term: 'pause',
    full: 'Freeze the simulator; state is preserved and you can resume from this point.'
  },
  stop: {
    term: 'stop',
    full: 'Halt the simulator and clear all metrics. Next play starts from scratch.'
  },

  // ── chaos ───────────────────────────────────────────────────────────
  faultKill: {
    term: 'kill',
    full: 'Crash the node. All requests routed to it fail immediately until you clear the fault.'
  },
  faultSlow: {
    term: 'slow',
    full: 'Multiply this node’s service time by 10×. Watch p99 explode and queues fill upstream.'
  },
  faultLoss: {
    term: 'loss',
    full: 'Randomly drop ~50% of requests reaching this node. Models flaky network or partial outages.'
  },
  faulted: {
    term: 'faulted',
    full: 'A fault is currently injected on this node. Click the same chaos button again to clear.'
  },

  // ── palette ─────────────────────────────────────────────────────────
  components: {
    term: 'components',
    full: 'Individual building blocks. Drag onto canvas or press Enter to insert at the center.'
  },
  templates: {
    term: 'templates',
    full: 'Pre-wired starter patterns — drop one to skip the boilerplate of connecting common topologies.'
  }
} as const satisfies Record<string, GlossaryEntry>;

export type Term = keyof typeof GLOSSARY;
